base_url = "https://designbylunar.github.io/cupid-ui"
title = "Cupid UI"
description = "Cupid UI is a modern framework for building responsive frontends."

default_language = "en"

compile_sass = true
generate_feed = false
minify_html = false

[markdown]
highlight_code = true
highlight_theme = "kronuz"

build_search_index = true

[extra]
author = "Lunar Design"
